"""add conversation summary and is_deleted

Revision ID: 8851df1fd8c0
Revises: 59a5ff701232
Create Date: 2026-05-14 20:36:29.931435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8851df1fd8c0'
down_revision = '59a5ff701232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('summary_updated_at')
        batch_op.drop_column('summary')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
